// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwfgdxztmrfgzenugeye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3ZmdkeHp0bXJmZ3plbnVnZXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzM5MDgsImV4cCI6MjA2MzY0OTkwOH0.gAJDPKmEu0PTZdue3PYhVD6Nx8r96mkXDjVeN8DlIQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);